mv_host: 'mohawk'

mv_database_name: 'mv_gefs_gdas_rtps_href_spring_2022'

model_names: ['href', 'gdas', 'gefs']

fcst_init_info:
    fcst_init_time_first: '2022050100'
    num_fcsts: 6
    fcst_init_intvl_hrs: 24

fcst_len_hrs: 36

vx_stats:
    #
    auc:
        apcp:
            03h:
                thresholds: ['gt0.0mm', 'ge2.54mm']
        dpt:
            2m:
                thresholds: ['ge288K', 'ge293K']
        refc:
            L0:
                thresholds: ['ge20dBZ', 'ge30dBZ', 'ge40dBZ', 'ge50dBZ']
        tmp:
            2m:
                thresholds: ['ge293K', 'ge298K']
            850mb:
                thresholds: ['ge288K']
        wind:
            10m:
                thresholds: ['ge5mps', 'ge10mps']
            700mb:
                thresholds: ['ge10mps']
    #
    bias:
        dpt:
            2m:
                thresholds: ['']
        refc:
            L0:
                thresholds: ['']
        tmp:
            2m:
                thresholds: ['']
            500mb:
                thresholds: ['']
            700mb:
                thresholds: ['']
            850mb:
                thresholds: ['']
        wind:
            10m:
                thresholds: ['']
            700mb:
                thresholds: ['']
            850mb:
                thresholds: ['']
    #
    brier:
        apcp:
            03h:
                thresholds: ['gt0.0mm', 'ge2.54mm']
        dpt:
            2m:
                thresholds: ['ge288K', 'ge293K']
        refc:
            L0:
                thresholds: ['ge20dBZ', 'ge30dBZ', 'ge40dBZ', 'ge50dBZ']
        tmp:
            2m:
                thresholds: ['ge293K', 'ge298K']
            850mb:
                thresholds: ['ge288K']
        wind:
            10m:
                thresholds: ['ge5mps', 'ge10mps']
            700mb:
                thresholds: ['ge10mps']
    #
    fbias:
        apcp:
            03h:
                thresholds: ['gt0.0mm', 'ge2.54mm']
        refc:
            L0:
                thresholds: ['ge20dBZ', 'ge30dBZ', 'ge40dBZ', 'ge50dBZ']
    #
    rely:
        apcp:
            03h:
                thresholds: ['gt0.0mm', 'ge0.508mm', 'ge2.54mm', 'ge6.35mm']
            06h:
                thresholds: ['ge6.35mm', 'ge12.7mm']
            24h:
                thresholds: ['ge25.4mm']
        dpt:
            2m:
                thresholds: ['ge288K', 'ge293K']
        refc:
            L0:
                thresholds: ['ge20dBZ', 'ge30dBZ', 'ge40dBZ']
        tmp:
            2m:
                thresholds: ['ge293K', 'ge298K', 'ge303K']
            850mb:
                thresholds: ['ge288K']
        wind:
            10m:
                thresholds: ['ge5mps', 'ge10mps']
            700mb:
                thresholds: ['ge10mps']
    #
    rhist:
        apcp:
            03h:
                thresholds: ['']
            06h:
                thresholds: ['']
            24h:
                thresholds: ['']
        cape:
            L0:
                thresholds: ['']
        dpt:
            2m:
                thresholds: ['']
        hgt:
            500mb:
                thresholds: ['']
        refc:
            L0:
                thresholds: ['']
        tmp:
            2m:
                thresholds: ['']
            500mb:
                thresholds: ['']
            850mb:
                thresholds: ['']
        wind:
            10m:
                thresholds: ['']
            500mb:
                thresholds: ['']
            850mb:
                thresholds: ['']
    #
    ss:
        apcp:
            03h:
                thresholds: ['']
        dpt:
            2m:
                thresholds: ['']
        hgt:
            500mb:
                thresholds: ['']
        refc:
            L0:
                thresholds: ['']
        tmp:
            2m:
                thresholds: ['']
            500mb:
                thresholds: ['']
            700mb:
                thresholds: ['']
            850mb:
                thresholds: ['']
        wind:
            500mb:
                thresholds: ['']
            700mb:
                thresholds: ['']
            850mb:
                thresholds: ['']

